name: linux

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Install Roswell
        run: |
          make linux-build archive
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: roswell-linux
          path: ./*.tbz
