name: osx

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.target == 'arm64' && 'macos-14' || 'macOS-12' }}
    strategy:
      fail-fast: false
      matrix:
        lisp: [sbcl-bin/2.4.0]
        target: [arm64, x86-64]
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          brew install automake autoconf
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          make roswell-sbcl sbcl
          make all archive
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: roswell-osx
          path: ./*.tbz
