name: osx

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          curl -L -O https://github.com/roswell/sbcl_bin/releases/download/2.4.0/sbcl-2.4.0-x86-64-darwin-binary.tar.bz2
          tar xf sbcl-2.4.0-x86-64-darwin-binary.tar.bz2
          cd sbcl-2.4.0-x86-64-darwin
          sh install.sh
          cd ..
          make sbcl
          make all archive
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: roswell-osx
          path: ./*.tbz
